#\!/bin/bash

echo "🔧 === CLEAN BUILD & REBUILD INSTRUCTIONS ==="
echo ""
echo "Option 1: Using Xcode GUI"
echo "========================="
echo "1. Open Xcode: open StudyAI.xcodeproj"
echo "2. Clean Build Folder: Shift+Cmd+K (or Product > Clean Build Folder)"
echo "3. Rebuild: Cmd+B"
echo "4. Run: Cmd+R"
echo ""
echo "Option 2: Using Command Line"
echo "============================"
echo "Run the following commands:"
echo ""
echo "# Clean derived data"
echo "rm -rf ~/Library/Developer/Xcode/DerivedData/StudyAI-*"
echo ""
echo "# Clean build folder"
echo "xcodebuild -project StudyAI.xcodeproj -scheme StudyAI -configuration Debug clean"
echo ""
echo "# Build fresh"
echo "xcodebuild -project StudyAI.xcodeproj -scheme StudyAI -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro' build"
echo ""
echo "# Run in Xcode (Cmd+R) after building"
echo ""
echo "🚨 IMPORTANT: After rebuilding, you MUST see these new log sections:"
echo "   - 🔍 === CALLING gradeSingleQuestion API ==="
echo "   - 🔍 === TASKGROUP RECEIVED RESULT ==="
echo "   - 🗄️ === STORING GRADE IN DICTIONARY ==="
echo "   - 🔍 === RETRIEVING GRADE FROM DICTIONARY ==="
echo "   - 🎴 === PROGRESSIVE SUBQUESTION CARD RENDERING ==="
echo ""
echo "If you don't see these, the old code is still running\!"
