//
//  DigitalHomeworkPDFPreviewView.swift
//  StudyAI
//
//  PDF Preview for Digital Homework Export
//  Shows preview with Print, Email, and Share options
//

import SwiftUI
import PDFKit
import MessageUI

struct DigitalHomeworkPDFPreviewView: View {
    let pdfDocument: PDFDocument
    let subject: String
    let questionCount: Int

    @State private var showingPrintOptions = false
    @State private var showingEmailComposer = false
    @State private var showingShareSheet = false
    @State private var pdfURL: URL?
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationView {
            VStack(spacing: 0) {
                // PDF Preview
                PDFKitView(document: pdfDocument)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)

                // Action Buttons
                HStack(spacing: 16) {
                    ActionButton(
                        icon: "printer.fill",
                        title: NSLocalizedString("pdfPreview.print", comment: "Print"),
                        color: .blue,
                        action: { handlePrint() }
                    )

                    ActionButton(
                        icon: "envelope.fill",
                        title: NSLocalizedString("pdfPreview.email", comment: "Email"),
                        color: .green,
                        action: { showingEmailComposer = true }
                    )

                    ActionButton(
                        icon: "square.and.arrow.up.fill",
                        title: NSLocalizedString("pdfPreview.share", comment: "Share"),
                        color: .orange,
                        action: { showingShareSheet = true }
                    )
                }
                .padding()
                .background(Color(.systemBackground))
                .shadow(color: .black.opacity(0.1), radius: 1, x: 0, y: -1)
            }
            .navigationTitle(NSLocalizedString("pdfPreview.title", comment: "PDF Preview"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button(NSLocalizedString("common.done", comment: "Done")) {
                        dismiss()
                    }
                }
            }
            .task {
                await savePDFToTempDirectory()
            }
            .sheet(isPresented: $showingEmailComposer) {
                if let url = pdfURL {
                    PDFMailComposeView(
                        subject: "StudyMates - \(subject) Digital Homework",
                        messageBody: createEmailBody(),
                        attachmentURL: url,
                        attachmentName: "digital-homework-\(subject.lowercased().replacingOccurrences(of: " ", with: "-")).pdf"
                    )
                }
            }
            .sheet(isPresented: $showingShareSheet) {
                if let url = pdfURL {
                    ShareSheet(items: [url])
                }
            }
        }
    }

    private func savePDFToTempDirectory() async {
        let tempDir = FileManager.default.temporaryDirectory
        let fileName = "digital-homework-\(subject.lowercased().replacingOccurrences(of: " ", with: "-"))-\(Date().timeIntervalSince1970).pdf"
        let url = tempDir.appendingPathComponent(fileName)

        if let data = pdfDocument.dataRepresentation() {
            do {
                try data.write(to: url)
                self.pdfURL = url
            } catch {
                print("Failed to save PDF to temp directory: \(error)")
            }
        }
    }

    private func createEmailBody() -> String {
        return """
        Hi there!

        I've attached my digital homework for \(subject) from StudyMates.

        Subject: \(subject)
        Number of questions: \(questionCount)
        Generated: \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none))

        Generated by StudyMates - Your AI Study Companion

        Best regards
        """
    }

    private func handlePrint() {
        guard let url = pdfURL else { return }

        let printController = UIPrintInteractionController.shared
        let printInfo = UIPrintInfo.printInfo()
        printInfo.outputType = .general
        printInfo.jobName = "StudyMates - \(subject) Digital Homework"

        printController.printInfo = printInfo
        printController.printingItem = url

        printController.present(animated: true) { (controller, completed, error) in
            if let error = error {
                print("Print error: \(error.localizedDescription)")
            }
        }
    }
}

// MARK: - Preview
#Preview {
    // Create a sample PDF document for preview
    let pdfDocument = PDFDocument()
    DigitalHomeworkPDFPreviewView(
        pdfDocument: pdfDocument,
        subject: "Mathematics",
        questionCount: 10
    )
}
