-- Add error analysis fields to questions table (used by passive reports)
-- NOT to archived_questions (which is unused in current architecture)

ALTER TABLE questions
  ADD COLUMN IF NOT EXISTS error_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS error_evidence TEXT,
  ADD COLUMN IF NOT EXISTS error_confidence FLOAT CHECK (error_confidence >= 0.0 AND error_confidence <= 1.0),
  ADD COLUMN IF NOT EXISTS learning_suggestion TEXT,
  ADD COLUMN IF NOT EXISTS error_analysis_status VARCHAR(20) DEFAULT 'pending'
    CHECK (error_analysis_status IN ('pending', 'processing', 'completed', 'failed', 'skipped')),
  ADD COLUMN IF NOT EXISTS error_analyzed_at TIMESTAMP;

-- Create index for report queries (passive reports filter by error type)
CREATE INDEX IF NOT EXISTS idx_questions_error_type
  ON questions(user_id, error_type)
  WHERE error_type IS NOT NULL;

-- Create index for finding mistakes by subject (for mistake notebook reports)
CREATE INDEX IF NOT EXISTS idx_questions_mistakes_by_subject
  ON questions(user_id, subject, error_analysis_status)
  WHERE error_analysis_status = 'completed';

-- Comments
COMMENT ON COLUMN questions.error_analysis_status IS
  'Status of error analysis: pending (awaiting), processing (in progress), completed (done), failed (error), skipped (correct answer)';
COMMENT ON COLUMN questions.learning_suggestion IS
  'Actionable learning advice generated by AI error analysis (Pass 2)';
COMMENT ON COLUMN questions.error_type IS
  'Error taxonomy category: conceptual_misunderstanding, procedural_error, calculation_mistake, etc.';
