# Dependency Update Workflow
# Automated dependency updates and security patches

name: Dependency Updates

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2 AM UTC
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  WORKING_DIRECTORY: ./01_core_backend

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates
        
      - name: Update dependencies
        run: |
          # Update patch and minor versions
          ncu -u --target minor
          npm install
          
      - name: Run tests after updates
        run: |
          npm test
          npm run lint
        continue-on-error: true
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates:
            
            - Updated patch and minor versions
            - Tests have been run to verify compatibility
            - Review and merge if all checks pass
            
            **Generated by GitHub Actions** 🤖
          branch: chore/dependency-updates
          delete-branch: true
          
  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Run security audit
        run: |
          npm audit --audit-level moderate
          npm audit fix --audit-level moderate
          
      - name: Create Security Update PR
        uses: peter-evans/create-pull-request@v5
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix vulnerabilities'
          title: 'security: automated security updates'
          body: |
            ## Automated Security Updates
            
            This PR contains automated security fixes:
            
            - Fixed security vulnerabilities found by npm audit
            - Please review and merge promptly
            
            **Generated by GitHub Actions** 🛡️
          branch: security/automated-fixes
          delete-branch: true